### ISSUE TITLE
the order in which these files are run

### ISSUE THREAD

**Issue by zzq2747** [Pe4enIks/TrainableActivation#2]
Dear @author, can you tell me the order in which these files are run?

**Comment by epishchik** [comment]
There are 3 main files - [train.py](https://github.com/Pe4enIks/TrainableActivation/blob/main/train.py), [test.py](https://github.com/Pe4enIks/TrainableActivation/blob/main/test.py), [plot.py](https://github.com/Pe4enIks/TrainableActivation/blob/main/plot.py). You should run train.py first, then test.py, then plot.py.  

Use whatever configuration you want to test. Configurations can be found in the [configs](https://github.com/Pe4enIks/TrainableActivation/tree/main/configs) folder, train.py and test.py use the same config. There are several plot configurations in the [configs/plot](https://github.com/Pe4enIks/TrainableActivation/tree/main/configs/plot) folder.

There are many predefined run scripts in the [scripts](https://github.com/Pe4enIks/TrainableActivation/tree/main/scripts) folder, just run one of them as .sh, [scripts/train.sh](https://github.com/Pe4enIks/TrainableActivation/blob/main/scripts/train.sh) and [scripts/test.sh](https://github.com/Pe4enIks/TrainableActivation/blob/main/scripts/test.sh) are scripts to train and test all possible configurations, [scripts/plot.sh](https://github.com/Pe4enIks/TrainableActivation/blob/main/scripts/plot.sh) to plot results after training and testing.

All the results of the train / test phases are in the [logs](https://github.com/Pe4enIks/TrainableActivation/tree/main/logs) folder.
